# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
# google-style-java formatting (version 1.7.0)
- repo: https://github.com/maltzj/google-style-precommit-hook
  sha: b7e9e7fcba4a5aea463e72fe9964c14877bd8130
  hooks:
  - id: google-style-java
